server:
  port: 8771
spring:
  profiles:
    active: dev
  application:
    name: admin-server
  boot:
    admin:
      turbine:
        cluster: default
        url: http://localhost:8781/turbine.stream
    routes:
      endpoints: env,metrics,trace,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,activiti
---
spirng:
  profiles: dev
### 此处dev先注册向其中一台注册中心###
  output:
    ansi:
     enable: true
eureka:
  client:
    service-url:
#      defaultZone: http://eureka-server1:8761/eureka/,http://eureka-server2:8762/eureka/,http://eureka-server3:8763/eureka/
      defaultZone: http://eureka-server1:8761/eureka/
    registry-fetch-interval-seconds: 60
  instance:
    lease-renewal-interval-in-seconds: 30
