spring:
  profiles: dev
  datasource:
    hikari:
      driver-class-name: com.mysql.jdbc.Driver
      password: jfz123456
      jdbc-url: jdbc:mysql://zxs-1:3306/dc?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8
      username: zxs
  rabbitmq:
    virtual-host: yujifang
    username: yujifang
    password: yujifang2017
    addresses: 10.1.2.101
    port: 5672
eureka:
  instance:
    hostname: user-service
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${server.port}}
  client:
    service-url:
      defaultZone: http://eureka-server1:8761/eureka/
    registry-fetch-interval-seconds: 60