server:
  port: 8781
spring:
  application:
    name: turbine-server
  profiles:
    active: dev
turbine:
  app-config: user-service,payment-service
  aggregator:
    cluster-config: default
  combine-host-port: true
  cluster-name-expression: default

---
spirng:
  profiles: dev
eureka:
  client:
    service-url:
#      defaultZone: http://eureka-server1:8761/eureka/,http://eureka-server2:8762/eureka/,http://eureka-server3:8763/eureka/
      defaultZone: http://eureka-server1:8761/eureka/
    registry-fetch-interval-seconds: 60
  instance:
    lease-renewal-interval-in-seconds: 30